---
version: '3'
services:
  check-formatting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-boilerplate
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      python -m black --line-length=100 --check /freqtrade/user_data/
    entrypoint: []
