---
version: '3'
services:
  check-formatting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-boilerplate
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      python -m black --line-length=100 --check /freqtrade/user_data/
    entrypoint: []
  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --timerange ${START_DATE:-20200101}-${END_DATE:-20220401}
      --timeframe 5m 15m 30m 1h 4h 1d 1w
      --config user_data/configs/pairlist-static-usdt-binance.json

  download-indicator-data:
    image: freqtradeorg/freqtrade:stable
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --timerange ${START_DATE:-20200101}-${END_DATE:-20220401}
      --timeframe 5m 15m 30m 1h 4h 1d 1w
      --config user_data/configs/pairlist-static-usdt-binance.json
      --pairs ETH/BTC ETH/USDT BTC/USDT
