name: Download data

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Cache download-data
      id: cache-download-data
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: user_data/data
        key: ${{ runner.os }}-download-data-${{ env.CACHE_NUMBER }}-${{ hashFiles('user_data/configs/pairlist-static-usdt-binance.json') }}

    - name: Downloading data
      if: steps.cache-download-data.outputs.cache-hit != 'true'
      run: |
        docker-compose run --rm download-indicator-data
        docker-compose run --rm download-data
