name: Python using Conda

on: [push]

jobs:
  build-linux:
    runs-on: self-hosted
    strategy:
      max-parallel: 2

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: freqtrade-conda
        python-version: 3.9
        channels: conda-forge
        allow-softlinks: true
        channel-priority: strict
        show-channel-urls: true
        use-only-tar-bz2: true
        auto-update-conda: false


    - name: Cache Entire Conda Environment
      id: cache-env
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0
      with:
        path: ${{ env.CONDA }}/envs
        key:
          ${{ runner.os }}-conda-environment-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Update Conda Environment
      if: steps.cache-env.outputs.cache-hit != 'true'
      env:
        ENVFILE: environment.yml
      shell: bash -l {0}
      run: conda env update -n freqtrade-conda -f $ENVFILE
